import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // Demo user
  const user = await prisma.user.upsert({
	where: { email: 'demo@studio.local' },
	update: {},
	create: { email: 'demo@studio.local', name: 'Demo User' }
  });

  // Placeholder image asset (points to a public placeholder; replace with your own)
  const image = await prisma.asset.create({
	data: {
	  kind: 'SOURCE_IMAGE',
	  bucketKey: 'uploads/demo-placeholder.jpg',
	  mime: 'image/jpeg'
	}
  });

  // Mock final video asset (points to a CDN/base + path you control)
  const final = await prisma.asset.create({
	data: {
	  kind: 'FINAL_VIDEO',
	  bucketKey: 'final/demo-video.mp4',
	  mime: 'video/mp4'
	}
  });

  // A completed job pointing to the assets above
  const job = await prisma.job.create({
	data: {
	  userId: user.id,
	  sourceImageId: image.id,
	  resultVideoId: final.id,
	  status: 'COMPLETE',
	  stage: 'COMPLETE',
	  prompt: 'Make a playful, cinematic intro of the uploaded photo. Add gentle camera push-in.',
	  promptPreset: 'Pixar-style intro',
	  voicePreset: 'alloy',
	  ttsScript: 'Welcome to the demo clip generated by our AI Studio.',
	  aspect: '16:9',
	  durationSec: 6
	}
  });

  // Share slug so the QR endpoint has something to resolve
  await prisma.share.create({
	data: {
	  jobId: job.id,
	  slug: 'demovideo'
	}
  });

  console.log('Seed complete. User:', user.email, 'Job:', job.id);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
}).finally(async () => {
  await prisma.$disconnect();
});